name: GitHub Actions Dev
on:
  push:
    branches:
      - "**"
      - "!main"
jobs:
  To-Ankiaddon:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create ankiaddon
        run: |
          ls
          cd MDKaTeX
          zip -r -q ../MDKaTeX.zip ./*
          cd ..
          mv MDKaTeX.zip MDKaTeX.ankiaddon
          ls

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MDKaTeX.ankiaddon
          path: ./MDKaTeX.ankiaddon